
name: sync_site

on:
  workflow_run:
    workflows: [pages/pages-build-deployment]
    types: [completed]
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pages-build-deployment
          workflow_conclusion: success
          name: github-pages
      - run: tar tf artifact.tar
   
