
name: sync_site

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: github-pages
      - run: tar tf artifact.tar
   
