
name: sync_site

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: shitshow
        with:
          result-encoding: string
          script: |
            console.log(context);
            const artifact_id = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.event.workflow.run_id,
              per_page: 1,
            });
            console.log(artifact_id);
            const artifact_url = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: artifact_id.data.artifacts[0].id,
              archive_format: "zip",
            });
            console.log(artifact_url);
            return artifact_url.headers["location"];
      - run: curl -sSLO ${{ steps.shitshow.outputs.result }}
      - run: ls -al
   
